var tutorial = {};

tutorial.cards = [
	{"id":"c-imyoidgx-nej355jggosce1n6w0s51xlxr","x":0,"y":0,"width":3,"height":7,"card_data":{"default_size":{"w":2,"h":2},"default_pos":{"x":4,"y":0},"card_content":{"title":"<b>Welcome to Ontology Cards</b><div>Here are few commands to start with</div>","text":"<img src=\"http://aka-minions-2015.gloryone.pl/au/gfx/images/delivery/minion_1.png\" alt=\"Image\" style=\" width:100%;\"><div>Ontology Cards is still being developed so it always may not work as you might expect, Any query or suggestions! send it to act.jnv@gmail.com &nbsp;&nbsp;<b style=\"font-size: 1em; line-height: 28.9px;\">OR </b><span style=\"font-size: 1em; line-height: 28.9px;\">&nbsp;file an issue in the github repo at:</span></div><div><a href=\"https://github.com/ashishact/Ontology-Cards\" target=\"_blank\">https://github.com/ashishact/Ontology-Cards</a></div>"},"model":"viewmodels/card","view":"views/cards/infobox.html","sctype":6},"TYPE":{"PARENT":false,"EDITABLE":true,"RESIZABLE":true,"MOVABLE":true,"DRAGGABLE":true,"EXPANDABLE":true,"VOLATILE":false,"TAB_SESSION_ONLY":false,"WINDOW_SESSION_ONLY":false}},
	{"id":"c-imyo4w8p-knjmzt7tdhyn0mteegp1wz5mi","x":3,"y":0,"width":5,"height":7,"card_data":{"default_size":{"w":2,"h":2},"default_pos":{"x":0,"y":0},"card_content":{"title":"<div>Basics Commands</div><div>Try out thse commands in the command input</div>","text":"<div><i>Note that you don't have to write full command</i></div>1. add My New Card (press enter)<div>2. add parent A parent Card&nbsp;<span style=\"line-height: 28.9px;\">(press enter)</span></div><div><span style=\"line-height: 28.9px;\">3. settext Adding some contents&nbsp;</span><span style=\"line-height: 28.9px;\">(press enter)</span></div><div><span style=\"line-height: 28.9px;\">4. add Minions&nbsp;</span><span style=\"line-height: 28.9px;\">(press enter)</span></div><div><span style=\"line-height: 28.9px;\">5. setimage&nbsp;</span>http://tny.im/4cz (press enter)</div><div><span style=\"line-height: 28.9px;\">6. add frame (press enter)</span></div>"},"model":"viewmodels/card","view":"views/cards/infobox.html","sctype":6},"TYPE":{"PARENT":false,"EDITABLE":true,"RESIZABLE":true,"MOVABLE":true,"DRAGGABLE":true,"EXPANDABLE":true,"VOLATILE":false,"TAB_SESSION_ONLY":false,"WINDOW_SESSION_ONLY":false}},
	{"id":"c-imyriq44-bl5sssy2kg5a0m2348lnv1jor","x":8,"y":0,"width":4,"height":7,"card_data":{"default_size":{"w":2,"h":2},"default_pos":{"x":0,"y":0},"card_content":{"title":"Explore","text":"<div><span style=\"line-height: 28.9px;\">1. add frame (press enter) [optional]</span><br></div><div>2. explore (press enter)</div><div><span style=\"line-height: 28.9px;\"><b>Instance Search</b></span><br></div><div>1. Isaac Newton (wait for suggestion)</div><div>2. Isaac Newton. (add a dot at the end) (wait for predicate suggestions)</div><div>3. Isaac Newton. birthPlace (note the dot ( . ) after Newton)</div><div>4. (wait for answer)</div><div>5. (Try some other queries)</div><div><b>Class based Search</b></div><div>1. All Scientist with birthPlace (wait for suggestion)</div><div>2. (Select one of the suggestions)</div><div>3..(Enter a dot &nbsp;\".\" )</div><div>4. (Enter one more dot \".\" )</div>"},"model":"viewmodels/card","view":"views/cards/infobox.html","sctype":6},"TYPE":{"PARENT":false,"EDITABLE":true,"RESIZABLE":true,"MOVABLE":true,"DRAGGABLE":true,"EXPANDABLE":true,"VOLATILE":false,"TAB_SESSION_ONLY":false,"WINDOW_SESSION_ONLY":false}},
	{"id":"c-imyoetmb-vxt0u2gm28etp8yd3ep2jra4i","x":0,"y":7,"width":4,"height":6,"card_data":{"default_size":{"w":2,"h":2},"default_pos":{"x":2,"y":0},"card_content":{"title":"Basic Interaction","text":"<div><b>Editing Cards</b></div>1. Click on any card to edit &nbsp;[but not a parent card]<div>2. A parent card has an arrow sign at bottom of the card<br><div>3. For Parent card click on the ellipses Icon (the one with three dots) at top right and click on \"Edit\" Icon</div></div><div><b>Remove a card</b></div><div>1. Click on the ( X ) Icon at top left to remove (but it will not delete it from database, It will appear again next time you come to this frameview )</div><div>2. If the Card is Selected Enter the command <i>remove </i>in the commandinput</div><div>3. To delete completely click on the ( X ) Icon with CTRL pressed &nbsp;or</div><div>4. enter the command <i>delete </i>&nbsp;and the selected card will be removed completely</div><div><b>Move and resize card</b></div><div>1. Click and drag any card to change its position</div><div>2. Click and drag at Bottom-left (or) Bottom-right corner to resize the card</div>"},"model":"viewmodels/card","view":"views/cards/infobox.html","sctype":6},"TYPE":{"PARENT":false,"EDITABLE":true,"RESIZABLE":true,"MOVABLE":true,"DRAGGABLE":true,"EXPANDABLE":true,"VOLATILE":false,"TAB_SESSION_ONLY":false,"WINDOW_SESSION_ONLY":false}},
	{"id":"c-imys7knx-dub74i3riw7347ko5rrdaemi","x":8,"y":7,"width":2,"height":4,"card_data":{"default_size":{"w":2,"h":2},"default_pos":{"x":4,"y":0},"card_content":{"title":"A Normal Card","text":"Click on me to edit.<div><br><div>You can add a card from the commandline by entering command \"add\"</div></div>"},"model":"viewmodels/card","view":"views/cards/infobox.html","sctype":6},"TYPE":{"PARENT":false,"EDITABLE":true,"RESIZABLE":true,"MOVABLE":true,"DRAGGABLE":true,"EXPANDABLE":true,"VOLATILE":false,"TAB_SESSION_ONLY":false,"WINDOW_SESSION_ONLY":false}},
	{"id":"c-imyoiq9d-k76sf0xtyhsgzgpl6gii9t3xr","x":10,"y":7,"width":2,"height":4,"card_data":{"parent":true,"default_size":{"w":2,"h":2},"default_pos":{"x":6,"y":0},"card_content":{"title":"Parent Card","text":"Click on me to enter a child view<div>press ESC to return to previous view</div><div>To add a parent card Enter the command add parent&nbsp;</div>"},"model":"viewmodels/card","view":"views/cards/infobox.html","sctype":6},"TYPE":{"PARENT":true,"EDITABLE":true,"RESIZABLE":false,"MOVABLE":true,"DRAGGABLE":true,"EXPANDABLE":false,"VOLATILE":false,"TAB_SESSION_ONLY":false,"WINDOW_SESSION_ONLY":false}},
]

tutorial.get_tutorial_card_titles = function(){
	var titles = [];
	for (var i = 0; i < tutorial.cards.length; i++) {
		var c = tutorial.cards[i];
		if(c.id && c.card_data && c.card_data.card_content){
			titles.push({id:'tutorial_'+ c.id, title:'Tutorial: ' + c.card_data.card_content.title});
		}
	}
	return titles;
}
